apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/minahaz-hub/nginx-dev.git
    targetRevision: main
    path: nginx
    helm :
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
